### ISSUE TITLE
[server] [feat] - api 문서 수정, posts 관련 함수 작성

### ISSUE THREAD

**Issue by usreon** [codestates/alive-curation#30]
### ISSUE
- Group: `server`
- Type: `update`, `feature`
- Detail: api 문서와 db 스키마 수정 후 Wiki에 재업로드 하겠습니다

### TODO
1. [x] editPosts 함수 구현
2. [x] deletePosts 함수 구현 
3. [x] 위에 언급한 문서 수정 후 wiki 업로드 

### Estimated Time
`3h`
